<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xslForOfficers.xsl"?>
<?xml-stylesheet type="text/xsl" href="xslForOwners.xsl"?>
<!DOCTYPE TEI [ 
    <!ELEMENT TEI (teiHeader,text+)>                  
    <!ELEMENT teiHeader (fileDesc)>
    <!ELEMENT fileDesc (titleStmt,publicationStmt,sourceDesc)>
    <!ELEMENT titleStmt (title,author,respStmt)>
    <!ELEMENT respStmt (resp,name)>   
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>    
    <!ELEMENT resp (#PCDATA)>
    <!ELEMENT name (#PCDATA|gloss|choice)*>
    <!ELEMENT publicationStmt (p+)>
    <!ELEMENT sourceDesc (p+)>
    
    <!ELEMENT text (front,body)>
    <!ELEMENT front (div1)>
    <!ELEMENT body (div1)>
    <!ELEMENT div1 ((note,head,opener)?|div2|surplus|num)*>
    <!ELEMENT note (#PCDATA|q|supplied)*>
    <!ELEMENT head (#PCDATA|name)*>
    <!ELEMENT opener (salute,byline,dateline)>
    <!ELEMENT salute (#PCDATA)>
    <!ELEMENT byline (#PCDATA|docAuthor)*>
    <!ELEMENT docAuthor (#PCDATA|supplied)*>
    <!ELEMENT dateline (#PCDATA|date)*>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT div2 (head,p*,div3*)>
    <!ELEMENT p (#PCDATA|note|surplus|desc)*>
    <!ELEMENT div3 (p+)>
    <!ELEMENT surplus (#PCDATA|div2)*>
    <!ELEMENT desc (#PCDATA|rs|addrName|num|gloss|name|choice)*>
    <!ELEMENT rs (#PCDATA|supplied|choice)*>
    <!ELEMENT choice (sic,corr)>
    <!ELEMENT sic (#PCDATA)>
    <!ELEMENT corr (#PCDATA)>
    <!ELEMENT addrName (#PCDATA)>
    <!ELEMENT num (#PCDATA|supplied)*>
    <!ELEMENT gloss (#PCDATA|span|name|gloss)*>
    <!ELEMENT span (#PCDATA)>
    <!ELEMENT q (#PCDATA)>
    <!ELEMENT supplied (#PCDATA)>
    
    <!ATTLIST TEI xmlns CDATA #REQUIRED
                  xml:lang CDATA #REQUIRED>
    <!ATTLIST div1 type CDATA #REQUIRED>
    <!ATTLIST note place CDATA #IMPLIED>
    <!ATTLIST head type CDATA #IMPLIED>
    <!ATTLIST date when CDATA #REQUIRED>
    <!ATTLIST name role CDATA #IMPLIED
                   xml:id ID #IMPLIED
                   ana CDATA #IMPLIED
                   type CDATA #IMPLIED>
                   
    <!ATTLIST rs type CDATA #REQUIRED>
    <!ATTLIST surplus reason CDATA #REQUIRED>
    <!ATTLIST desc rend CDATA #REQUIRED>
    <!ATTLIST num type CDATA #REQUIRED
                  value CDATA #REQUIRED>
    <!ATTLIST gloss type CDATA #REQUIRED
                    target CDATA #REQUIRED>
    <!ATTLIST q rend CDATA #REQUIRED>  
    <!ATTLIST span style CDATA #REQUIRED> 
]>

<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:lang="en">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Restaurant Recommendation</title>
                <author>Time Out London Food &amp; Drink</author>
                <respStmt>
                    <resp>encoder</resp>
                    <name>20053281</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Unpublished, this corpus is only used for academics.</p>
            </publicationStmt>
            <sourceDesc>
                <p>all texts are collected from https://www.timeout.com/london; detailed URLs are provided in the note of each text.</p>
            </sourceDesc>
        </fileDesc>
    </teiHeader>
    
    <!-- [ 10 texts are included in this corpus, all gives a detailed recommendation list of restaurants in London ...] -->   

    <!-- [ text 1 Chinatown ...] -->   
    <text> 
        <front>
            <div1 type="abstract">
                <note place="top">https://www.timeout.com/london/restaurants/where-to-eat-in-chinatown</note>
                <head type="title">Chinatown</head>
                <opener>
                    <salute>Dine at the finest Chinese spots the London’s Chinatown has to offer (plus a few-non Chinese options, too)</salute>              
                    <byline>By <docAuthor>Time Out London Food &amp; Drink</docAuthor></byline> 
                    <dateline>Posted: <date when="2019-04-24">Wednesday April 24 2019</date></dateline>               
                </opener>    
            </div1>
        </front>
        
        <body>
            <!-- [ body of text 1 ... ] -->           
            <div1 type="main">
                <num type='avgPrice' value="1.7"><supplied>￡-￡￡</supplied></num>
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="A1">BaoziInn Romilly Street</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Soho</addrName> <num type="price" value="1">￡</num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">It’s all about the buns at <gloss type="environment" target="#A1">this <span style="color:#11A2A7">basement Chinese street-food restaurant</span>, a little sister to the Newport Court BaoziInn round the corner</gloss>. The <name role="specialty" xml:id="A1.1" type="small plates">bao</name> as they should be: <gloss type="cuisine" target="#A1.1"><span style="color:#11A2A7">soft</span> and <span style="color:#11A2A7">fluffy</span> on the outside; <span style="color:#11A2A7">deliciously warm</span>, <span style="color:#11A2A7">sweet</span> and <span style="color:#11A2A7">sticky</span> on the inside</gloss>.<gloss type="tips" target="#A1">Take a date for <span style="color:#11A2A7">pre-theatre beers and bao</span>, and you’ll do very well here</gloss>.</desc></p>
                        <p><note place="bottom">Venue says <q rend="italics">From the heart of Northern China to the heart of London; Our chefs are famed for the authenticity of their cooking</q>!</note></p>
                        <p><surplus reason="invalid">Discover Sohos favourite Read more</surplus></p>
                    </div3>                  
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A2">Café TPT</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Chinatown</addrName> <num type="price" value="3"><supplied>￡￡￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal">Big menus are commonplace in Chinatown, but <gloss type="menu" target="#A2">such <span style="color:#11A2A7">a vast repertoire</span> seems impossible</gloss> from <gloss type="environment" target="#A2">a galley <span style="color:#11A2A7">the size of an origami boat</span></gloss>. Still, <gloss type="menu" target="#A2">TPT manages to <span style="color:#11A2A7">deliver its pan-Chinese bonanza with commendable aplomb</span></gloss>. Best bets are <gloss type="cuisine" target="#A2.1">Cantonese staples such as <span style="color:#11A2A7">succulent</span></gloss> <name role="specialty" xml:id="A2.1" type="rice noodles">roast duck on rice</name>, although we crave the <gloss type="cuisine" target="#A2.2">Hong Kong-style</gloss> ‘<name role="specialty" xml:id="A2.2" type="dishes">Tai pai tong hawker dishes</name>’ too.</desc></p>                   
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A3">Canton</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Chinatown</addrName> <num type="price" value="1"><supplied>￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal">It may be <gloss type="environment" target="#A3">getting <span style="color:#11A2A7">ragged round the edges</span></gloss>, but this <gloss type="environment" target="#A3"><span style="color:#11A2A7">plainly furnished</span> Chinatown veteran</gloss> is once again on song – especially when it comes to its famed <name role="specialty" xml:id="A3.1" type="rice noodles">one-plate rice and noodle dishes</name> <gloss type="cuisine" target="#A3.1">piled high with <span style="color:#11A2A7">juicy meats</span> (roast duck, barbecued pork, soy chicken etc)</gloss>. <gloss type="service" target="#A3">Service is <span style="color:#11A2A7">noticeably friendly</span> and accommodating by Chinatown standards</gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>                    
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A4">C&amp;R Café</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Malaysian</rs> <addrName>Chinatown</addrName> <num type="price" value="1">￡</num></desc></p>
                    <div3>
                        <p><desc rend="normal">C&amp;R slipped quietly into a Chinatown alley more than two decades ago, bringing with it <gloss type="menu" target="#A4">a <span style="color:#11A2A7">passion</span> for <name role="specialty" xml:id="A4.1" type="dishes">Malaysian laksa</name></gloss>: <gloss type="cuisine" target="#A4.1"><span style="color:#11A2A7">giant</span> bowls of <span style="color:#11A2A7">spicy</span> coconutty broth packed with <span style="color:#11A2A7">juicy prawns</span>,<span style="color:#11A2A7">thin rice vermicelli</span>, <span style="color:#11A2A7">puffy fish balls</span>, the works</gloss>. It also serves up <gloss type="cuisine" target="#A4.2"><span style="color:#11A2A7">umami-rich</span></gloss> plates of <name role="specialty" xml:id="A4.2" type="rice noodles">char kway teow noodles</name>, piled-high <name role="specialty" xml:id="A4.3" type="rice noodles">rice-based nasi goreng</name>, <name role="specialty" xml:id="A4.4" type="baked">buttery roti canai bread</name> and the <gloss type="cuisine" target="#A4.5"><span style="color:#11A2A7">celebrated</span></gloss> <name role="specialty" xml:id="A4.5" type="dishes">beef rendang</name>. <gloss type="service" target="#A4">C&amp;R's vibe is <span style="color:#11A2A7">functional but contemporary</span>, while staff are <span style="color:#11A2A7">friendly but terrifyingly efficient</span></gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>                    
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A5">Dumplings’ Legend</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style"><supplied>Chinese</supplied></rs> <addrName>Chinatown</addrName> <num type="price" value="2"><supplied>￡￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal">Never tried <name role="specialty" xml:id="A5.1" type="small plates">xiao long bau</name>? Sometimes called <gloss type="cuisine" target="#A5.1">‘soup dumplings’, these Shanghai <span style="color:#11A2A7">beauties</span> are steamed parcels containing both filling and broth ­­– so be sure to <span style="color:#11A2A7">pop</span> them in your mouth in one go</gloss>. The classic pork version is our favourite, while dim sum fans will also like DL’s moreish <name role="specialty" xml:id="A5.2" type="small plates">fried turnip cake</name> and quivering <name role="specialty" xml:id="A5.3" type="small plates">cheung fun</name>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                    
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A6">Gerrard’s Corner</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs><addrName>Chinatown</addrName> <num type="price" value="2"><supplied>￡￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal"><gloss type="menu" target="#A6">Dumplings are the stars of the show</gloss> at <gloss type="environment" target="#A6">this <span style="color:#11A2A7">unpretentious</span> joint on the corner of Gerrard Street</gloss>, <name role="specialty" xml:id="A6.1" type="small plates">prawn and chive dumplings</name> are <gloss type="cuisine" target="#A6.1"><span style="color:#11A2A7">plump</span> and <span style="color:#11A2A7">sweet</span>, while their <span style="color:#11A2A7">rich crabmeat</span> cousins come with a scallop balanced on top</gloss>. If you like your <gloss type="menu" target="#A6">dim sum with a side of <span style="color:#11A2A7">nostalgia</span></gloss>, adorably retro Gerrard’s is for you.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>                   
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A7">Imperial China</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Chinatown</addrName> <num type="price" value="3"><supplied>￡￡￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal"><gloss type="environment" target="#A7">A <span style="color:#11A2A7">small wooden bridge</span> spanning an <span style="color:#11A2A7">ornamental fish pond</span>, <span style="color:#11A2A7">warm wood panelling</span>, <span style="color:#11A2A7">kind lighting</span> and a second floor offering <span style="color:#11A2A7">a view of the dining room below</span> set this Cantonese standby apart from its Chinatown rivals</gloss>. <gloss type="menu" target="#A7">The food is <span style="color:#11A2A7">reliable</span>, <span style="color:#11A2A7">authentic</span> and of <span style="color:#11A2A7">decent quality</span> – even if <span style="color:#11A2A7">portions can seem rather miserly</span></gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>                   
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A8">Jen Café</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Chinatown</addrName> <num type="price" value="1">￡</num></desc></p>
                    <div3>
                        <p><desc rend="normal">Although this <gloss type="environment" target="#A8"><span style="color:#11A2A7">green-painted</span> café </gloss><gloss type="menu" target="#A8">serves everything</gloss> from <name role="specialty" xml:id="A8.2" type="baked">buttered toast</name> and <name role="specialty" xml:id="A8.3" type="dishes">barbecued pork</name> to <name role="specialty" xml:id="A8.4" type="beverages">bubble teas</name>, it’s the hand-wrapped <name role="specialty" xml:id="A8.1" type="small plates">dumplings</name> that keep us coming back. <gloss type="cuisine" target="#A8.1">The <span style="color:#11A2A7">cheapest</span> are the jiao zi (aka ‘Beijing dumplings’) – eight morsels filled to <span style="color:#11A2A7">bursting</span> with <span style="color:#11A2A7">pork or vegetables</span> for a <span style="color:#11A2A7">fiver</span></gloss>. You guessed it, they’re one of our go-to Chinatown snacks.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>                    
                </div2>
                
                <div2>
                    <head type="sub"><name role="restaurant" xml:id="A9">Le Hanoi</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Chinese</rs> <addrName>Chinatown</addrName> <num type="price" value="2"><supplied>￡￡</supplied></num></desc></p>
                    <div3>
                        <p><desc rend="normal"><gloss type="environment" target="#A9"><span style="color:#11A2A7">Cheap</span> and <span style="color:#11A2A7">cheerful</span></gloss> is an increasingly rare commodity in Chinatown, but this casual Vietnamese joint could change all that. <gloss type="menu" target="#A9">We’ll forgive one rather bland pho, because some <span style="color:#11A2A7">positively classy food</span> is on offer here</gloss> – from <gloss type="cuisine" target="#A9.1"><span style="color:#11A2A7">juicy</span></gloss> <name role="specialty" xml:id="A9.1" type="small plates">prawn summer rolls</name> and <name role="specialty" xml:id="A9.2" type="small plates">pork dumplings wrapped in betel leaves</name> to an <gloss type="cuisine" target="#A9.3">utterly <span style="color:#11A2A7">zesty</span></gloss> <name role="specialty" xml:id="A9.3" type="dishes">mango salad with crispy shrimps</name>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3> 
                </div2>
            </div1>
        </body> 
    </text>
    
    
    
    <!-- [ text 2 kings-cross...] -->
    <text> 
        <front>
            <div1 type="abstract">
                <note place="top"><supplied>https://www.timeout.com/london/restaurants/kings-cross-restaurants</supplied></note>
                <head type="main">King’s Cross</head>
                <opener>
                    <salute>Discover the top restaurants, cafés and gastropubs around King's Cross</salute>              
                    <byline><docAuthor><supplied>Time Out London Food &amp; Drink</supplied></docAuthor></byline> <dateline>Posted: <date when="2019-05-21">Tuesday May 21 2019</date></dateline>               
                </opener>    
            </div1>
        </front>
        
        <body> 
            <!-- [ body of text 2 ... ] -->
            <div1 type="main">   
                <num type='avgPrice' value="2.2"><supplied>￡￡</supplied></num>
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B1">Aux Pains de Papy</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Bakeries</corr></choice></rs> <rs type="style">French</rs> <addrName>Gray’s Inn Road</addrName> <num type="price" value="1"><supplied>￡</supplied></num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">A trip to Paris on the Eurostar might be the best way to indulge in an ooh-la-la French café experience, but what’s the next best thing A trip to King’s Cross and <gloss type="environment" target="#B1">a visit to this <span style="color:#11A2A7">endearing little café</span> – a mere boule’s-throw from the Eurostar terminal</gloss>. Aux Pains de Papy already has <gloss type="tips" target="#B1">a loyal following of office workers</gloss> seeking their <name role="specialty" xml:id="B1.1" type="baked">daily bread</name> and <gloss type="cuisine" target="#B1.2"><span style="color:#11A2A7">satisfying</span> lunchtime</gloss> <name role="specialty" xml:id="B1.2" type="fast food">sandwiches</name>, but it’s also worth seeking out for <name role="specialty" xml:id="B1.3" type="desserts">patisserie</name> and <name role="specialty" xml:id="B1.4" type="baked">boulangerie</name>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B2">Barrafina King’s Cross</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Spanish</rs> <addrName>King’s Cross</addrName> <num type="price" value="3">￡￡￡</num></desc></p>                            
                    <div3>
                        <p><desc rend="normal"><gloss type="menu" target="#B2">Spanish mini chain Barrafina has been <span style="color:#11A2A7">breaking foodie hearts</span></gloss> ever since it first arrived on Frith Street way back in 2007. This branch, <gloss type="environment" target="#B2">on the upper level of Coal Drops Yard, comes with <span style="color:#11A2A7">outdoor seating</span> to soak up the sun, and in a Barrafina first, there are even <span style="color:#11A2A7">two tables for four inside</span></gloss>. Don’t miss the <gloss type="cuisine" target="#B2.1"><span style="color:#11A2A7">eggy</span>, <span style="color:#11A2A7">gooey</span></gloss> <name role="specialty" xml:id="B2.1" type="fast food">tortilla</name> and the classic <name role="specialty" xml:id="B2.2" type="small plates">croquetas</name> <gloss type="cuisine" target="#B2.2">filled with <span style="color:#11A2A7">rich</span>, Spanish-style blood pudding</gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B3">Caravan King's Cross</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Coffee&amp;tea</corr></choice></rs> <rs type="style"><choice><sic>Cafés</sic><corr>Fusion</corr></choice></rs> <addrName>King’s Cross</addrName> <num type="price" value="2"><supplied>￡￡</supplied></num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">Compared to some of its other branches, the King’s Cross offshoot of <gloss type="environment" target="#B3">Caravan is a <span style="color:#11A2A7">grandiose urbane proposition</span> – all <span style="color:#11A2A7">concrete floors</span>, <span style="color:#11A2A7">girders and exposed pipework</span>. The <span style="color:#11A2A7">industrial-themed interior</span> isn’t built for intimacy, but it still has a <span style="color:#11A2A7">laid-back buzz</span> and great <span style="color:#11A2A7">people-watching opportunities</span></gloss>. As expected, <gloss type="service" target="#B3">this outlet boasts <span style="color:#11A2A7">welcoming, efficient staff</span></gloss> and <gloss type="menu" target="#B3">a menu of what they call ‘<span style="color:#11A2A7">well-travelled food</span>’ – ie <span style="color:#11A2A7">plates of global fusion</span></gloss> ranging from <name role="specialty" xml:id="B3.1" type="dishes">lamb ribs with chermoula</name> to <name role="specialty" xml:id="B3.2" type="dishes">Burmese chicken salad</name>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B4">Casa Pastor</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Mexican</rs> <addrName>King’s Cross</addrName> <num type="price" value="2">￡￡</num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">Eat as many <name role="specialty" ana="#B4.1" type="fast food">tacos</name> at you can at Casa Pastor, <gloss type="menu" target="#B4">a <span style="color:#11A2A7">massive Mexican restaurant at Coal Drops Yard</span></gloss> from the team behind much-loved El Pastor in Borough Market. The <gloss type="environment" target="#B4.2"><span style="color:#11A2A7">addictive</span>, <span style="color:#11A2A7">slightly chewy</span></gloss> <name role="specialty" xml:id="B4.2" type="fast food">corn tortillas</name> are <gloss type="cuisine" target="#B4.2">made <span style="color:#11A2A7">in-house</span>: order a bunch of them, topped with the likes of <span style="color:#11A2A7">juicy</span> pork shoulder and pineapple, and lightly-battered sea bass</gloss> then feast on some <gloss type="cuisine" target="#B4.3"><span style="color:#11A2A7">crispy</span>, <span style="color:#11A2A7">sugary</span></gloss> <name role="specialty" xml:id="B4.3" type="desserts">churros</name> with <gloss type="cuisine" target="#B4.3">warm chocolate sauce</gloss> for pud.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B5">Coal Office</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice></rs> <rs type="style">Middle Eastern</rs> <addrName>King’s Cross</addrName> <num type="price" value="3">￡￡￡</num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">Fan of The Palomar and The Barbary? Then you’ll love Coal Office, <gloss type="environment" target="#B5">a swish Tom Dixon-designed spot at Coal Drops Yard</gloss> with some of <gloss type="menu" target="#B5"><span style="color:#11A2A7">the city’s best Middle Eastern food</span></gloss>. <gloss type="menu" target="#B5"><span style="color:#11A2A7">Everything is bold and memorable</span></gloss> here: expect delights like <name role="specialty" xml:id="B5.1" type="dishes">fennel with a yoghurt-harissa dressing</name> and <gloss type="cuisine" target="#B5.2">seriously good</gloss> puds; <name role="specialty" xml:id="B5.2" type="desserts">rice pudding</name> with <gloss type="cuisine" target="#B5.2">flavours of <span style="color:#11A2A7">mango</span> and <span style="color:#11A2A7">kaffir lime</span></gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>            
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B6">Dishoom</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice><supplied> Bars</supplied></rs> <rs type="style">Indian</rs> <addrName>King’s Cross</addrName> <num type="price" value="3"><supplied>￡￡￡</supplied></num></desc></p>                            
                    <div3>
                        <p><desc rend="normal"><gloss type="environment" target="#B6"><span style="color:#11A2A7">Whirling ceiling fans</span>, <span style="color:#11A2A7">vintage Indian magazine ads</span> and other <span style="color:#11A2A7">retro wheezes</span> set the scene for some <span style="color:#11A2A7">post-colonial romping</span> at this swish London take on <span style="color:#11A2A7">an old ‘Irani café’</span>. It’s all very <span style="color:#11A2A7">design-conscious and slick</span></gloss>, but there’s no arguing with the food – <gloss type="menu" target="#B6">a <span style="color:#11A2A7">spicy all-day repertoire</span></gloss> running from <name role="specialty" xml:id="B6.1" type="small plates">bhel pooris</name> to <name role="specialty" xml:id="B6.2" type="rice noodles">biryanis</name>. <gloss type="tips" target="#B6">Expect <span style="color:#11A2A7">crazy queues in the evenings</span> (check booking restrictions), though the <span style="color:#11A2A7">basement bar</span> is a godsend</gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>              
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B7">Granger &amp; Co</name></head>
                    <p><desc rend="bold"><rs type="occasion"><choice><sic>Restaurants</sic><corr>Casual dining</corr></choice><supplied> Brunch</supplied></rs> <rs type="style">Fusion</rs> <addrName>King’s Cross</addrName> <num type="price" value="2">￡￡</num></desc></p>                            
                    <div3>
                        <p><desc rend="normal">The King’s Cross outpost of Aussie Bill Granger's <gloss type="menu" target="#B7"><span style="color:#11A2A7">all-day sunny-side-up eatery references</span> just about every <span style="color:#11A2A7">on-trend fad and fashion on the current foodie agenda</span></gloss>: small plates, grains, <name role="specialty" xml:id="B7.1" type="dishes">Korean riffs</name>, <name role="specialty" xml:id="B7.2" type="rice noodles">Hawaiian-style poké bowls</name>, <name role="specialty" xml:id="B7.3" type="dishes">Thai curries</name> and all sorts of multicultural stuff besides. Granger is also known for giving <gloss type="menu" target="#B7">good brunch</gloss>, and this spot has <gloss type="environment" target="#B7">the added bonus of <span style="color:#11A2A7">in-demand alfresco tables on a quiet piazza</span></gloss>.</desc></p>
                        <p><surplus reason="invalid">Read more</surplus></p>
                    </div3>
                </div2>                     
                
                <div2>
                    <head type="subtitle"><name role="restaurant" xml:id="B8">Hicce</name></head>